# Generated by Django 3.2.11 on 2024-10-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('approved', models.BooleanField(default=False)),
                ('weekday', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('area', models.CharField(choices=[('CI', 'Channel Islands Area'), ('CTV', 'Chiltern & Thames Valley Area'), ('CA', 'Cornwall Area'), ('DA', 'Devon Area'), ('DO', 'Dorset Area'), ('EMA', 'East Midlands Area'), ('ES', 'Essex Area'), ('FC', 'Free Counties Area'), ('GM', 'Greater Manchester Area'), ('HA', 'Hampshire Area'), ('KE', 'Kent Area'), ('L-EC', 'Lancashire - East & Central Area'), ('L-NE', 'London - North East Area'), ('L-NW', 'London - North West Area'), ('L-SE', 'London - South East Area'), ('L-SW', 'London - South West Area'), ('MEA', 'Merseyside Area'), ('NS', 'Norfolk & Suffolk Area'), ('NEE', 'North East England Area'), ('NW', 'NW England & N Wales Area'), ('S-EC', 'Scotland - East Coast Area'), ('S-EL', 'Scotland - Edinburgh & Lothians Area'), ('S-GW', 'Scotland - Glasgow & West Coast Area'), ('S-WL', 'Scotland - West Lothian Area'), ('SWA', 'South Wales Area'), ('SU', 'Surrey Area'), ('SX', 'Sussex Area'), ('HIG', 'The Highlands & Islands Groups'), ('TS', 'The Shires Area'), ('UK-FAR', 'UK Farsi Groups Area'), ('WC', 'West Country Area'), ('WM', 'West Midlands Area'), ('WY', 'West Yorkshire'), ('YH', 'Yorkshire & Humberside Area')], default='CI', max_length=20)),
                ('description', models.TextField()),
                ('online_meeting_url', models.URLField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mosaicminds.meetings',
            },
        ),
    ]
