# Generated by Django 5.0 on 2024-01-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meeting',
            table='mosaicminds.meetings',
        ),
    ]
